type AuthPayload {
  accessToken: String!
  expiresIn: Int!
  refreshToken: String!
  user: User!
}

type BeltEvent {
  dog: Dog
  id: ID!
  occurredAt: Date!
  order: Order
  review: Review
  subjectId: ID!
  type: BeltEventType!
  user: User
}

enum BeltEventType {
  DOG_CREATED
  DOG_DELETED
  DOG_UPDATED
  ORDER_ACCEPTED
  ORDER_CANCELLED
  ORDER_CREATED
  ORDER_FINISHED
  ORDER_PAID
  ORDER_STARTED
  ORDER_UPDATED
  REVIEW_CREATED
  USER_UPDATED
}

input CancelOrderInput {
  reason: String
}

input CreateDogInput {
  behaviorTags: [DogBehavior!]! = []
  name: String!
  notes: String
  size: DogSize!
}

input CreateOrderInput {
  dogId: ID!
  endTime: Date!
  estimatedDurationMinutes: Int
  locationAddress: String!
  locationLat: Float!
  locationLng: Float!
  priceAmount: Int!
  priceCurrency: String! = "EUR"
  startTime: Date!
}

input CreateReviewInput {
  comment: String
  rating: Int!
}

"""Date custom scalar type"""
scalar Date

type Dog {
  behaviorTags: [DogBehavior!]!
  createdAt: Date!
  id: ID!
  name: String!
  notes: String
  ownerId: ID!
  size: DogSize!
  updatedAt: Date!
}

enum DogBehavior {
  AGGRESSIVE
  FRIENDLY
  NEEDS_EXPERIENCED_WALKER
  REACTIVE
}

enum DogSize {
  LARGE
  MEDIUM
  SMALL
}

input LoginInput {
  password: String!
  phone: String!
}

input LogoutInput {
  refreshToken: String!
}

type Mutation {
  acceptOrder(id: ID!): Order!
  cancelOrder(id: ID!, input: CancelOrderInput): Order!
  createDog(input: CreateDogInput!): Dog!
  createOrder(input: CreateOrderInput!): Order!
  createOrderReview(input: CreateReviewInput!, orderId: ID!): Review!
  deleteDog(id: ID!): Boolean!
  finishOrder(id: ID!): Order!
  login(input: LoginInput!): AuthPayload!
  logout(input: LogoutInput!): Boolean!
  markOrderPaid(id: ID!): Order!
  refreshSession(input: RefreshSessionInput!): AuthPayload!
  register(input: RegisterInput!): AuthPayload!
  startOrder(id: ID!): Order!
  updateDog(id: ID!, input: UpdateDogInput!): Dog!
  updateMyRoles(input: UpdateMyRolesInput!): User!
}

type Order {
  acceptedAt: Date
  cancelledAt: Date
  createdAt: Date!
  dogId: ID!
  endTime: Date!
  finishedAt: Date
  id: ID!
  locationAddress: String!
  locationLat: Float!
  locationLng: Float!
  ownerId: ID!
  paidAt: Date
  priceAmount: Int!
  priceCurrency: String!
  startTime: Date!
  startedAt: Date
  status: OrderStatus!
  updatedAt: Date!
  walkerId: ID
}

enum OrderStatus {
  ACCEPTED
  CANCELLED
  CREATED
  FINISHED
  PAID
  STARTED
}

type Query {
  availableOrders: [Order!]!
  dog(id: ID!): Dog!
  me: User!
  myDogs: [Dog!]!
  myOwnerOrders(statuses: [OrderStatus!]): [Order!]!
  myReviews: [Review!]!
  myWalkerOrders(statuses: [OrderStatus!]): [Order!]!
  order(id: ID!): Order!
}

input RefreshSessionInput {
  refreshToken: String!
}

input RegisterInput {
  password: String!
  phone: String!
  roles: [UserRole!]!
}

type Review {
  comment: String
  createdAt: Date!
  id: ID!
  orderId: ID!
  rating: Int!
  revieweeId: ID!
  reviewerId: ID!
}

type Subscription {
  beltEvent: BeltEvent!
}

input UpdateDogInput {
  behaviorTags: [DogBehavior!]
  name: String
  notes: String
  size: DogSize
}

input UpdateMyRolesInput {
  roles: [UserRole!]!
}

type User {
  createdAt: Date!
  id: ID!
  isVerified: Boolean!
  phone: String!
  rating: Float!
  roles: [UserRole!]!
  updatedAt: Date!
}

enum UserRole {
  OWNER
  WALKER
}
