import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateBeltTables20260427180000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DO $$
      BEGIN
        CREATE TYPE belt_user_role AS ENUM ('OWNER', 'WALKER');
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        CREATE TYPE dog_size AS ENUM ('SMALL', 'MEDIUM', 'LARGE');
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        CREATE TYPE dog_behavior AS ENUM (
          'FRIENDLY',
          'REACTIVE',
          'AGGRESSIVE',
          'NEEDS_EXPERIENCED_WALKER'
        );
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        CREATE TYPE order_status AS ENUM (
          'CREATED',
          'ACCEPTED',
          'STARTED',
          'FINISHED',
          'PAID',
          'CANCELLED'
        );
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS belt_user (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        phone varchar(32) NOT NULL UNIQUE,
        roles belt_user_role[] NOT NULL DEFAULT '{}',
        rating double precision NOT NULL DEFAULT 0,
        is_verified boolean NOT NULL DEFAULT false,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS dog (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_id integer NOT NULL REFERENCES belt_user(id) ON DELETE CASCADE,
        name varchar(80) NOT NULL,
        size dog_size NOT NULL,
        behavior_tags dog_behavior[] NOT NULL DEFAULT '{}',
        notes varchar(500),
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS walk_order (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_id integer NOT NULL REFERENCES belt_user(id) ON DELETE RESTRICT,
        walker_id integer REFERENCES belt_user(id) ON DELETE SET NULL,
        dog_id integer NOT NULL REFERENCES dog(id) ON DELETE RESTRICT,
        status order_status NOT NULL DEFAULT 'CREATED',
        price_amount integer NOT NULL,
        price_currency varchar(3) NOT NULL DEFAULT 'EUR',
        location_lat double precision NOT NULL,
        location_lng double precision NOT NULL,
        location_address varchar(240) NOT NULL,
        start_time timestamptz NOT NULL,
        end_time timestamptz NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        accepted_at timestamptz,
        started_at timestamptz,
        finished_at timestamptz,
        cancelled_at timestamptz,
        paid_at timestamptz,
        CONSTRAINT chk_walk_order_price_amount_non_negative
          CHECK (price_amount >= 0),
        CONSTRAINT chk_walk_order_time_range
          CHECK (end_time > start_time),
        CONSTRAINT chk_walk_order_walker_required_after_acceptance
          CHECK (
            status IN ('CREATED', 'CANCELLED')
            OR walker_id IS NOT NULL
          )
      )
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS order_review (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id integer NOT NULL REFERENCES walk_order(id) ON DELETE CASCADE,
        reviewer_id integer NOT NULL REFERENCES belt_user(id) ON DELETE CASCADE,
        reviewee_id integer NOT NULL REFERENCES belt_user(id) ON DELETE CASCADE,
        rating integer NOT NULL,
        comment varchar(500),
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT uq_order_review_order_reviewer
          UNIQUE (order_id, reviewer_id),
        CONSTRAINT chk_order_review_rating_range
          CHECK (rating >= 1 AND rating <= 5),
        CONSTRAINT chk_order_review_not_self
          CHECK (reviewer_id <> reviewee_id)
      )
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE walk_order
          ADD CONSTRAINT chk_walk_order_price_amount_non_negative
          CHECK (price_amount >= 0);
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE walk_order
          ADD CONSTRAINT chk_walk_order_time_range
          CHECK (end_time > start_time);
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE walk_order
          ADD CONSTRAINT chk_walk_order_walker_required_after_acceptance
          CHECK (
            status IN ('CREATED', 'CANCELLED')
            OR walker_id IS NOT NULL
          );
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE order_review
          ADD CONSTRAINT uq_order_review_order_reviewer
          UNIQUE (order_id, reviewer_id);
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE order_review
          ADD CONSTRAINT chk_order_review_rating_range
          CHECK (rating >= 1 AND rating <= 5);
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);
    await queryRunner.query(`
      DO $$
      BEGIN
        ALTER TABLE order_review
          ADD CONSTRAINT chk_order_review_not_self
          CHECK (reviewer_id <> reviewee_id);
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_dog_owner_id ON dog(owner_id)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_walk_order_owner_status
        ON walk_order(owner_id, status)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_walk_order_walker_status
        ON walk_order(walker_id, status)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_walk_order_available
        ON walk_order(created_at)
        WHERE status = 'CREATED' AND walker_id IS NULL
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_order_review_reviewee_id
        ON order_review(reviewee_id)
    `);

    await queryRunner.query(`
      INSERT INTO belt_user (id, phone, roles, is_verified)
      VALUES
        (1, '+3725550001', ARRAY['OWNER']::belt_user_role[], true),
        (2, '+3725550002', ARRAY['WALKER']::belt_user_role[], true),
        (3, '+3725550003', ARRAY['OWNER', 'WALKER']::belt_user_role[], true)
      ON CONFLICT (id) DO UPDATE
      SET
        phone = EXCLUDED.phone,
        roles = EXCLUDED.roles,
        is_verified = EXCLUDED.is_verified
    `);
    await queryRunner.query(`
      SELECT setval(
        pg_get_serial_sequence('belt_user', 'id'),
        GREATEST((SELECT COALESCE(MAX(id), 1) FROM belt_user), 3),
        true
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS order_review');
    await queryRunner.query('DROP TABLE IF EXISTS walk_order');
    await queryRunner.query('DROP TABLE IF EXISTS dog');
    await queryRunner.query('DROP TABLE IF EXISTS belt_user');
    await queryRunner.query('DROP TYPE IF EXISTS order_status');
    await queryRunner.query('DROP TYPE IF EXISTS dog_behavior');
    await queryRunner.query('DROP TYPE IF EXISTS dog_size');
    await queryRunner.query('DROP TYPE IF EXISTS belt_user_role');
  }
}
