import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateAuthTables20260428110000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS auth_account (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id integer NOT NULL REFERENCES belt_user(id) ON DELETE CASCADE,
        provider varchar(64) NOT NULL,
        provider_subject varchar(191) NOT NULL,
        password_hash varchar(255),
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_account_provider_subject
        ON auth_account(provider, provider_subject)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_auth_account_user_id
        ON auth_account(user_id)
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS auth_refresh_token (
        id uuid PRIMARY KEY,
        user_id integer NOT NULL REFERENCES belt_user(id) ON DELETE CASCADE,
        token_hash varchar(128) NOT NULL,
        expires_at timestamptz NOT NULL,
        revoked_at timestamptz,
        replaced_by_token_id uuid,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_refresh_token_hash
        ON auth_refresh_token(token_hash)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_user_id
        ON auth_refresh_token(user_id)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_expires_at
        ON auth_refresh_token(expires_at)
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS auth_refresh_token');
    await queryRunner.query('DROP TABLE IF EXISTS auth_account');
  }
}
