import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateNotifications20260428110948 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DO $$
      BEGIN
        CREATE TYPE notification_type AS ENUM (
          'AVAILABLE_WALK_CREATED',
          'ORDER_ACCEPTED',
          'ORDER_STARTED',
          'ORDER_FINISHED',
          'ORDER_CANCELLED',
          'ORDER_PAID',
          'REVIEW_CREATED'
        );
      EXCEPTION WHEN duplicate_object THEN NULL;
      END $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS user_notification (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        recipient_id integer NOT NULL REFERENCES belt_user(id) ON DELETE CASCADE,
        type notification_type NOT NULL,
        title varchar(120) NOT NULL,
        body varchar(300) NOT NULL,
        action_url varchar(200),
        order_id integer REFERENCES walk_order(id) ON DELETE SET NULL,
        actor_id integer REFERENCES belt_user(id) ON DELETE SET NULL,
        read_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_user_notification_recipient_created_at
        ON user_notification(recipient_id, created_at DESC)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_user_notification_recipient_read_at
        ON user_notification(recipient_id, read_at)
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS user_notification');
    await queryRunner.query('DROP TYPE IF EXISTS notification_type');
  }
}
